import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        white_smoke: "#F5F5F5",
        charcoal_black: "#242731",
        gainsboro_gray: "#F4F5F6",
        jet_black: "#1F2128",
        amethyst_purple: "#A162F7",
        amethyst_purple_transparent: "#A162F71A",
        lavender_gray: "#F5F4F6",
        dark_charcoal: "#2B2E38",
        vivid_orange: "#FF764C",
        cool_gray: "#7C7C8D",
        light_gray_blue: "#E0E4E7",
        slate_gray: "#5F6165",
        gunmetal_gray: "#2C303D",
        azure_blue: "#438FFE",
        medium_spring_green: "#70CF97",
        vibrant_yellow: "#F6CC0D",
        onyx_gray: "#323745",
        storm_gray: "#808191",
        dark_charcoal_a: "#333",
        dark_slate_gray: "#2A2D36",
        charcoal_blue: "#292E3D",
        off_white: "#F3F5F8",
        light_gray: "#A4A5A6",
        dove_gray: "#72767C",
        light_off_white: "#F3F3F3",
        light_coral_red: "#FF6370",
        crimson_red: "#D43B3B",
        light_sky_blue: "#C6DCFC",
        sky_blue: "#579BFF",
        light_gray_blue_a: "#ECEEF0",
        light_red: "#FF5A5A",
        light_grayish_blue: "#B1B5C3",
        vivid_blue: "#4776D0",
        dusty_blue: "#777E90",
        pale_gray_blue: "#B4B4C6",
        off_white_light: "#F9F9F9",
        light_coral_red_a: "#F65E5E",
        light_pink_red: "#FAAEAE",
        light_gray_blue_b: "#E9EAEC",
        vivid_blue_a: "#2884FF",
        transparent_black: "#0F0F0F0D",
        soft_beige: "#E1DFA4",
        pale_blue_gray: "#E3ECF1",
        light_rose_pink: "#F4E3E5",
        semi_transparent_white: "#FFFFFFCC",
        jet_black_a: "#0F0F0F",
        white_overlay: "#FFFFFFE5",

        white_translucent: "#FFFFFF80",
        white_light_translucent: "#FFFFFF1A",
        pure_white: "#FFFFFF",
        light_gray_a: "#D6D6D6",
        silver_gray: "#C0C0C0",
        dim_gray: "#737373",
        black_translucent: "#00000080",
        off_white_a: "#F6F6F6",
        light_red_a: "#FF6464",
        pale_blue: "#E7ECF3",
        soft_cream: "#EFEBF1",
        charcoal_gray_dark: "#464155",
        lavender_gray_a: "#D8D2E7",
        light_silver: "#ECECEC",
        slate_gray_a: "#72767C",
        light_silver_gray: "#E1E1E1",
        vivid_blue_light: "#407EF9",
        vivid_blue_light_translucent: "#407EF91A",
        soft_pink_red_translucent: "#FF7E861A",


      },
      animation: {
        spinCustom: "spinCustom 1s linear infinite",
      },
      keyframes: {
        spinCustom: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
