export const IMAGES = {
  HOME_HEADING: "/assets/home-heading.png",
  NAVBAR_LOGO: "/assets/Heading.png",
  WORK_IMAGE: "/assets/works-image.png",
  SELL_CAR: "/assets/sell-car.png",
  OIL_LEVEL: "/assets/oil-level.png",
  BRAKE_PAD: "/assets/brake-pad.png",
  STEERING: "/assets/steering.png",
  ACTIVITY_GRAPH: "/assets/activity-graph.png",
  AVATOR: "/assets/avator.png",
  AVATOR_IMG: "/assets/avator-sec.png",
  CHART: "/assets/chart.png",
  CIRCLE: "/assets/circle.png",
  SERVICE_TIME_GRAPH: "/assets/service-time-graph.png",
  LIGHTNING_ICON: "/icons/lightning-icon.png",
  DASHBOARD_CARD_ICON: "/icons/dashboard-card-icon.png",
  BLOOD_ICON: "/icons/blood-icon.png",
  TIER_ICON: "/icons/tier-icon.png",
  SERVICE_ICON_CARD: "/icons/service-icon-card.png",
};
